//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaDetay
    {
        public int FaturaDetaylarID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<short> Miktar { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> FaturaID { get; set; }
    }
}
