//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int GelirlerID { get; set; }
        public Nullable<System.DateTime> GelirTarihi { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
    }
}
