//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int GiderlerID { get; set; }
        public string GiderTuruAdi { get; set; }
        public Nullable<System.DateTime> Tarihi { get; set; }
        public Nullable<decimal> GiderTutari { get; set; }
        public string Aciklama { get; set; }
    }
}
