//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilceler
    {
        public int ilcelerID { get; set; }
        public string ilceAdi { get; set; }
        public int ilID { get; set; }
    }
}
