//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotlarID { get; set; }
        public Nullable<System.DateTime> NotTarihi { get; set; }
        public Nullable<System.TimeSpan> NotSaati { get; set; }
        public string NotBaslik { get; set; }
        public string NotDetay { get; set; }
        public string NotuOlusturan { get; set; }
    }
}
