//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonellerID { get; set; }
        public string TC { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Adres { get; set; }
    }
}
