//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personelizinleri
    {
        public int PersonelizinleriID { get; set; }
        public Nullable<System.DateTime> izinBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> izinBitisTarihi { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string izinAciklamasi { get; set; }
        public Nullable<int> YillikIzinGunSayisi { get; set; }
        public Nullable<int> KalanIzınGunSayisi { get; set; }
    }
}
