//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelMesaileri
    {
        public int PersonelMesaileriID { get; set; }
        public Nullable<System.DateTime> MesaiTarihi { get; set; }
        public Nullable<decimal> MesaiSuresi { get; set; }
        public Nullable<int> PersonelMaasBilgisiID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<decimal> ToplamMesaiUcreti { get; set; }
    }
}
