//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatislarID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<System.DateTime> islemTarihi { get; set; }
        public Nullable<System.TimeSpan> islemSaat { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> indirimOrani { get; set; }
        public string indirimAciklamasi { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> GelirID { get; set; }
    }
}
