//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SirketBankaBilgileri
    {
        public int SirketBankaBilgileriID { get; set; }
        public int SirketID { get; set; }
        public int BankaID { get; set; }
        public string Iban { get; set; }
        public string HesapNo { get; set; }
        public string BankaYetkiliAdiSoyadi { get; set; }
        public string HesapTuru { get; set; }
    }
}
