//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiketOtomasyonu.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirketler
    {
        public int SirketlerID { get; set; }
        public string SirketAdi { get; set; }
        public string YetkiliGorevi { get; set; }
        public string YetkiliAdiSoyadi { get; set; }
        public string SirketTelefon1 { get; set; }
        public string SirketTelefon2 { get; set; }
        public string EMail { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string VergiDairesi { get; set; }
        public string Adres { get; set; }
    }
}
